localFile:
  sources:
  - plugin: file
    path: ./testfile.json
  destinations:
  - plugin: stdout
  - plugin: file
    path: ./outfile.json
  processors:
  - stage: 1
    steps:
    - step: 2
      workflow:
      - driver: json
        method: transform
        fieldActions:
          - path: tmp
            action: drop()
    - step: 1
      workflow:
      - driver: json
        method: extract
        driverActions:
          addVars:
            user: foobar7
          addFields:
            rank: 10
            numbers: ["one", "two", "three"]
          addTags:
            foo: bar
        driverConditions:
          ifVars:
            user: matchString(foobar7)
          ifFields:
            rank: 10
            numbers: ["one", "two", "three"]
          ifTags:
            foo: bar





